package comp3111.covid;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.Tab;
import javafx.scene.control.TextArea;
import javafx.scene.control.TextField;
import javafx.scene.control.ToggleGroup;
import javafx.application.Application;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.scene.Scene;
import javafx.scene.control.CheckMenuItem;
import javafx.scene.control.ListView;
import javafx.scene.control.MenuButton;
import javafx.scene.control.SelectionMode;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * Building on the sample skeleton for 'ui.fxml' Controller Class generated by SceneBuilder 
 */
public class Controller {

    @FXML
    private Button importCSV;
    
    @FXML
    private Button buttonConfirmedCases;

    @FXML
    private Button buttonConfirmedDeaths;

    @FXML
    private Button buttonRateOfVaccination;

    
    
    @FXML
    private ListView<String> countryEntry;
    //private String[] countries = {"Hong Kong0","Hong Kong1","Hong Kong2","Hong Kong3","Hong Kong4"};
    private List<String> countries2 = DataAnalysis.getUniqueLocations();
    private ObservableList<String> countryList = FXCollections.observableArrayList(countries2);
    

    
    
    
    @FXML
    private TextField dateEntry;

    @FXML
    private Button generate;

    @FXML
    private Tab tabApp1;

    @FXML
    private Tab tabApp2;

    @FXML
    private Tab tabApp3;

    @FXML
    private Tab tabReport1;

    @FXML
    private Tab tabReport2;

    @FXML
    private Tab tabReport3;

    @FXML
    private Tab tabTaskZero;

    @FXML
    private TextArea textAreaConsole;

    @FXML
    private TextField textfieldDataset;

    @FXML
    private TextField textfieldISO;

    @FXML
    void doImportCSV(ActionEvent event) {
    	String iDataset = textfieldDataset.getText();
    	DataAnalysis.setClass(iDataset);
    	
    	System.out.print( "Test End" + "\n");

    	countries2 = DataAnalysis.getUniqueLocations();
    	countryList = FXCollections.observableArrayList(countries2);
    	

    	initialize();
    }
    
    private 
    /**
     *  Task Zero
     *  To be triggered by the "Confirmed Cases" button on the Task Zero Tab 
     *  
     */
    @FXML
    void doConfirmedCases(ActionEvent event) {
    	String iDataset = textfieldDataset.getText();
    	String iISO = textfieldISO.getText();
    	String oReport = DataAnalysis.getConfirmedCases(iDataset, iISO);
    	textAreaConsole.setText(oReport);
    }
  
    /**
     *  Task Zero
     *  To be triggered by the "Confirmed Deaths" button on the Task Zero Tab
     *  
     */
    @FXML
    void doConfirmedDeaths(ActionEvent event) {
    	String iDataset = textfieldDataset.getText();
    	String iISO = textfieldISO.getText();
    	String oReport = DataAnalysis.getConfirmedDeaths(iDataset, iISO);
    	textAreaConsole.setText(oReport);
    }

 
    /**
     *  Task Zero
     *  To be triggered by the "Rate of Vaccination" button on the Task Zero Tab
     *  
     */
    @FXML
    void doRateOfVaccination(ActionEvent event) {
    	String iDataset = textfieldDataset.getText();
    	String iISO = textfieldISO.getText();
    	String oReport = DataAnalysis.getRateOfVaccination(iDataset, iISO);
    	textAreaConsole.setText(oReport);
    }
    
    @FXML
    void generateTableA(ActionEvent event) {
    	textAreaConsole.clear();

    	String date;
    	if (dateEntry.getText() == null || dateEntry.getText().trim().isEmpty()) {
    		textAreaConsole.appendText("Please Enter a Date" + "\n");
    		return;
    		
    	}
    	else {
    		date = dateEntry.getText();
        	dateEntry.clear();
    	}
    	textAreaConsole.appendText( "Countries:" + "\n");
    	for (Integer i : countryEntry.getSelectionModel().getSelectedIndices()) {
        	textAreaConsole.appendText( countryList.get(i) + "\n");
    	}
    	
    	textAreaConsole.appendText( "\nDate:\n" + date + "\n");
    	textAreaConsole.appendText( "Generating Table for task A"+ "\n");
    	
    	// private void generateTable(List<String> countries, String){}
    	//{"Hong Kong", "India"}, "6/20/2021"
    } 
    
    @FXML 
    private void generate() {
    	
    }
    
    @FXML
    public void initialize() {
    	countryEntry.setItems(countryList);
  
    	countryEntry.getSelectionModel().setSelectionMode(SelectionMode.MULTIPLE);    	
    }
}

